http:
 port: "8081"
 
db:
 mySQL:
   accountName: "la02440.ap-southeast-1"
   warehouse: "COMPUTE_WH"
   database: "Banking"
   schema: "BFS"
   user: "DK90"
   password: "Reward890"
   role: "ACCOUNTADMIN"
  
email:
 config:
   Host: "smtp.gmail.com"
   Port: "587"
   User: "devendra.varshney.ind@gmail.com"
   Password: "kqvedlrfsichqxmn"
   